version: '3.9'

services:
  website:
    container_name: "php-malek-web"
    image: php:8.0-fpm
    volumes:
      - /home/malik/development-labs/containerize/malek-my-id/app:/var/www
    #  - ${PWD}:var/www
    working_dir: /var/www
  
  nginx:
    container_name: "nginx-malek-web"
    image: nginx:latest
    volumes:
      - /home/malik/development-labs/containerize/malek-my-id/app:/var/www
      - /home/malik/development-labs/containerize/malek-my-id/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #  - ${PWD}:var/www
    #  - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 10000:80

